backend:
  name: git-gateway
  branch: master

media_folder: "static/images/uploads"
public_folder: "images/uploads"

# Define a collection - NetlifyCMS will creat json format blog posts

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "static/posts"
    create: true
    extension: json
    format: json
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      - {field: "tags", value: "css"}
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "portfolio"
    label: "Portfolio Projects"
    folder: "static/projects"
    create: true
    extension: json
    format: json
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
