backend:
  name: git-gateway
  branch: master

media_folder: "static/images/uploads"
public_folder: "images/uploads"

# Define a collection - NetlifyCMS will creat json format blog posts

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "static/posts"
    create: true
    extension: json
    format: json
    slug: "{{slug}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Slug", name: "slug", widget: "hidden", default: slug}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Alt Text", name: "altText", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
  - name: "portfolio"
    label: "Portfolio Projects"
    folder: "static/projects"
    create: true
    extension: json
    format: json
    slug: "{{slug}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "project"}
      - {label: "Slug", name: "slug", widget: "hidden", default: "{{slug}}"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Alt Text", name: "altText", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
